name: Deploy

on:
  push:
    branches:
      - feat/gh-actions-setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    name: run deploy on node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm test
      - run: npm run build

      - uses: netlify/actions/cli@master
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          with:
            args: deploy --dir=build --prod
            secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'